# Generated by Django 5.2.5 on 2025-08-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('sonarr_url', models.URLField(blank=True, null=True)),
                ('sonarr_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('radarr_url', models.URLField(blank=True, null=True)),
                ('radarr_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_host', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_port', models.PositiveIntegerField(blank=True, null=True)),
                ('mail_secure', models.CharField(blank=True, choices=[('', 'Kein TLS/SSL'), ('starttls', 'STARTTLS'), ('ssl', 'SSL/TLS')], max_length=10, null=True)),
                ('mail_user', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_password', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_from', models.EmailField(blank=True, max_length=254, null=True)),
                ('acc_username', models.CharField(blank=True, max_length=150, null=True)),
                ('acc_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
