# Generated by Django 5.2.5 on 2025-08-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingspanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='jellyfin_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='jellyfin_server_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
