# Generated by Django 5.2.5 on 2025-08-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingspanel', '0003_alter_appsettings_mail_secure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='mail_secure',
            field=models.CharField(blank=True, choices=[('', 'No TLS/SSL'), ('starttls', 'STARTTLS (Port 587)'), ('ssl', 'SSL/TLS (Port 465)'), ('tls', 'TLS (alias STARTTLS)')], max_length=10, null=True),
        ),
    ]
