# Generated by Django 5.2.5 on 2025-09-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingspanel', '0008_appsettings_youtube_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='recent_activity_days',
            field=models.PositiveSmallIntegerField(default=15, help_text='Number of days to look back for recent downloads on the homepage.'),
        ),
    ]
