# Generated by Django 5.2.5 on 2025-09-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingspanel', '0009_appsettings_recent_activity_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='recent_notifications_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Number of days to look back for recent notifications on the homepage.'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='recent_activity_days',
            field=models.PositiveSmallIntegerField(default=15, help_text='Number of days to look back for recently downloaded movies and series on the homepage.'),
        ),
    ]
