# Generated by Django 5.2.5 on 2025-09-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingspanel', '0010_appsettings_recent_notifications_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='show_ended_series_days',
            field=models.PositiveSmallIntegerField(default=2, help_text='Show ended series for this many days after they ended (0 = hide immediately).'),
        ),
    ]
