# Generated by Django 5.2.5 on 2025-08-19 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('channel', 'Channel'), ('playlist', 'Playlist')], max_length=16)),
                ('target_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yt_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'target_id'], name='youtube_you_kind_ad43df_idx')],
                'unique_together': {('user', 'kind', 'target_id')},
            },
        ),
        migrations.CreateModel(
            name='YTSentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=64)),
                ('published_date', models.DateField()),
                ('title', models.CharField(max_length=300)),
                ('channel_title', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['video_id'], name='youtube_yts_video_i_702538_idx')],
                'unique_together': {('user', 'video_id')},
            },
        ),
    ]
